=== Da-hub-hub/WebTest/src/main/resources/testcase/testcase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.supaur.com/testcase"
        xmlns:tns="http://www.supaur.com/testcase"
        elementFormDefault="qualified">
    <element name="Uitestcase">
        <complexType>
            <sequence>
                <element name="testcase" type="tns:testcase" minOccurs="0"
                         maxOccurs="1">
                    <annotation>
                        <documentation>
                            testcase根元素！
                        </documentation>
                    </annotation>
                </element>
            </sequence>
        </complexType>
    </element>

    <!--testcase-->
    <complexType name="testcase">
        <sequence>
            <element name="test" type="tns:test" minOccurs="0"
                     maxOccurs="unbounded">
                <annotation>
                    <documentation> testcase编写规则
                    </documentation>
                </annotation>
            </element>
        </sequence>
        <attribute name="url" type="string" use="required"/>
    </complexType>

    <!--test-->
    <complexType name="test">
        <sequence>
            <element name="assert" type="tns:assert" minOccurs="0"
                     maxOccurs="unbounded">
                <annotation>
                    <documentation> testcase编写规则
                    </documentation>
                </annotation>
            </element>
        </sequence>
        <attribute name="operator" type="tns:operator" use="required" />
        <attribute name="param" type="string"  />
        <attribute name="type" type="tns:type" use="required" />
        <attribute name="value" type="string" use="required" />
        <attribute name="desc" type="string" use="required" />
        <attribute name="name" type="string" use="required" />
        <attribute name="handle" type="string"  />
    </complexType>

    <!--test中operator的枚举值-->
    <simpleType name="operator">
        <restriction base="string">
            <enumeration value="click" />
            <enumeration value="sendKeys" />
            <enumeration value="clear" />
            <enumeration value="navigate" />
            <enumeration value="alert" />
            <enumeration value="confirm" />
            <enumeration value="iframe" />
            <enumeration value="systemAssert" />
            <enumeration value="elementAssert" />
        </restriction>
    </simpleType>

    <!--test中type的枚举值-->
    <simpleType name="type">
        <restriction base="string">
            <enumeration value="id" />
            <enumeration value="name" />
            <enumeration value="xpath" />
            <enumeration value="className" />
            <enumeration value="linkText" />
            <enumeration value="cssSelector" />
            <enumeration value="tagName" />
        </restriction>
    </simpleType>








    <!--assert-->
    <complexType name="assert">
        <attribute name="type" type="tns:type2" use="required" />
        <attribute name="expectValue" type="string" use="required" />
    </complexType>
    <!--断言中type的枚举值-->
    <simpleType name="type2">
        <restriction base="string">
            <enumeration value="text" />
            <enumeration value="value" />
            <enumeration value="isDisplay" />
        </restriction>
    </simpleType>
    <!--assert-->






</schema>

=== Da-hub-hub/WebTest/src/main/resources/testcase/test.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Uitestcase xmlns="http://www.supaur.com/testcase">
    <testcase url="https://cdp.dmp-sit.supaur.tech/overview/customer"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.supaur.com/testcase testcase.xsd">
        <!--
        现阶段：参数类型均为String
        type:元素定位类型
        value:定位元素所需要的参数
        handle:切换至第几个页面
        desc：描述（用来打印日志）
        name：元素名称，暂未用到
        timeout:超时时间，暂未用到
        -->
        <test type="xpath"  value="//input[@placeholder='用户名']"  desc="用户名输入框" name="输入用户名" operator="sendKeys" param="15003970273"/>
        <test type="xpath"  value="//input[@placeholder='密码']"  desc="密码输入框" name="输入密码" operator="sendKeys" param="Supaur2021!@#"/>
        <test type="xpath"  value="//button[1]"  desc="登录" name="登录" operator="click" param=""/>
        <test type="xpath" value="//li[text()='增长参谋']" desc="增长参谋" name="增长参谋" operator="click" param=""/>
        <test type="xpath" value="//li/span[text()='活动']" desc="活动" name="活动" operator="click" param=""/>
        <test  value="//li/span[text()='活动']" desc="活动" name="活动" operator="click" param="" type="xpath"></test>
        <test  value="//span[text()='标签管理']"  desc="进入标签管理" handle="1" operator="click" name="" type="xpath"/>

    </testcase>
</Uitestcase>
